### ISSUE TITLE
Возможность создавать собственные модули

### ISSUE THREAD

**Issue by HamletSargsyan** [ArtyomKingmang/Lazurite#21]
Возможность разделить  программу на несколько файлов, чтобы весь код не был в одном файле. Это улучшит организацию и структуру проекта.

Как это будет выглядеть: 

main.lzr
```lazurite
using "./myModule"

greet("Hamlet")
```

myModule.lzr
```lazurite
func greet(name) {
    print("Hello " + name + "!")
}
```

**Comment by ArtyomKingmang** [comment]
Функция для подключения сторонних файлов для использования его функций уже есть, и реализовано при помощи ключевого слова "include"

**Comment by HamletSargsyan** [comment]
> Функция для подключения сторонних файлов для использования его функций уже есть, и реализовано при помощи ключевого слова "include"

В документации об этом нечего не нашел. Блогодарю за ответ
