### ISSUE TITLE
Command not found!

### ISSUE THREAD

**Issue by TheBestUser01234567890** [ArtyomKingmang/Lazurite#43]
Everything I try to run, it says `Command not found!`. I have checked and lazurite is in my path. It runs normally without arguments.

OS: Linux Mint 20.3 Una (x86_64)
Shell: bash 5.0.17
Terminal: gnome-terminal

Lazurite version: 2.7.4 (.jar)

My modifications: I moved the jar from `~/Downloads/Lazurite.jar` to `/usr/bin/lazurite`.

**Comment by RadiationX** [comment]
Try not to write "--" in the arguments.
For example
`java -jar Lazurite.jar run test.lzr`
or
`java -jar Lazurite.jar -r test.lzr`

**Comment by TheBestUser01234567890** [comment]
`java -jar Lazurite.jar run test.lzr` or `java -jar Lazurite.jar -r test.lzr`

>My modifications: I moved the jar from ~/Downloads/Lazurite.jar to /usr/bin/lazurite.

Also I didn't write --, and you can run a java executable on linux without putting "java" before it.
