### ISSUE TITLE
Будет ли мобильный редактор кода?

### ISSUE THREAD

**Issue by Sambomancpp** [ArtyomKingmang/Lazurite#50]
Хотелось бы иметь возможность редактировать и запускать код на лазурите с телефона, это даст хороший буст не только к аудитории, у которых не часто есть доступ к пк, но и + компактность. Не обязательно делать какой-то очень крутой редактор, достаточно будет подсветки синтаксиса, запуска и работы с файлами (чтобы их можно было загружать в проект из приложения)

**Comment by ArtyomKingmang** [comment]
Очень вряд-ли. Сам я не мобильный разработчик, а потому не в моим силах сделать хорошую ide. У меня были идеи для написания библиотеки для работы с графикой андроида и сборку в апк. Если найдется человек, который согласится сделать ide, то я займусь библиотекой и сборщиком, а пока что у меня другие планы
