### ISSUE TITLE
Определить и внедрить метод версионирования для проекта.

### ISSUE THREAD

**Issue by HamletSargsyan** [ArtyomKingmang/Lazurite#61]
Выберите и внедрите один из стандартных методов версионирования для проекта. Это поможет обеспечить согласованность и прозрачность релизов, а также упростит поддержку проекта и взаимодействие с пользователями.

## Рекомендации по выбору метода:

 -  [Semantic Versioning (SemVer)](https://semver.org/lang/ru/): Использует формат `MAJOR.MINOR.PATCH` для указания изменений в проекте. Подходит, если важно различать несовместимые изменения, добавление новых функций и исправление ошибок.
-  [Calendar Versioning (CalVer)](https://calver.org/): Основан на дате выпуска и используется в формате `YYYY.MM.DD` или подобном. Полезен, если проект следует регулярному циклу выпусков.

## Почему это важно:

- Удобство и стандартизация: Чётко определённая схема версионирования облегчит разработку и поддержку утилит, связанных с проектом. Это также упростит понимание и планирование релизов для команды и пользователей.

- Снижение рисков: Использование стандартизированной схемы версионирования помогает избежать недопонимания и конфликтов при интеграции с другими проектами и инструментами, которые полагаются на версию для определения совместимости и поддержки.

**Comment by ArtyomKingmang** [comment]
Да, пожалуй это хорошая идея
